name: Require Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate_check_list:
    runs-on: ubuntu-latest
    steps:
      - uses: quangly1691/action-check-pr-desc@v1.1
